networks:
  postgres_db-network:
    external: true
  gitea:
    external: false
  proxy-ntwk:
    external: true

services:
  gitea:
    container_name: gitea
    image: docker.gitea.com/gitea:1.24.4-rootless
    restart: always
    user: "${UID}:${GID}"
    environment:
      # - USER_UID=1000
      # - USER_GID=1000
      - USER_UID=966
      - USER_GID=966
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWORD}
    networks:
      - postgres_db-network
      - gitea
      - proxy-ntwk
    ports:
      - "10037:3000"
      - "9022:2222"
    volumes:
      - ${GITEA_DATA_VOLUME}/gitea-data:/var/lib/gitea
      - ${GITEA_DATA_VOLUME}/gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


  runner:
    image: gitea/act_runner:nightly
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "${INSTANCE_URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "${RUNNER_NAME}"
      GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
    networks:
      - gitea
    depends_on:
      - gitea
    volumes:
      - ${GITEA_DATA_VOLUME}/gitearunner-data:/data
      - ${GITEA_DATA_VOLUME}/gitearunner-config/config.yaml:/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
#   gitea-data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ${GITEA_DATA_VOLUME}
