name: llama-cpp
services:
  llama.cpp:
    volumes:
      - models-volume:/models
    ports:
      - 10040:8080
    image: ghcr.io/ggml-org/llama.cpp:server-openvino
    command: -m /models/7B/ggml-model-q4_0.gguf --port 8080 --host 0.0.0.0 -n 512

volumes:      
  models-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MODELS_VOLUME}