name: llama-cpp
services:
  llama.cpp:
    volumes:
      - models-volume:/models
    ports:
      - 10040:${LLAMA_SERVER_PORT}
    # image: ghcr.io/ggml-org/llama.cpp:server-openvino
    image: ghcr.io/ggml-org/llama.cpp:server
    command: ${COMMAND_PARAM}

volumes:      
  models-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MODELS_VOLUME}